# Generated by Django 4.2.10 on 2026-03-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-utensils', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=20)),
                ('min_level', models.FloatField(default=5.0)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cooking', 'Cooking'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField()),
                ('authorized_by', models.CharField(default='Manager', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Restaurant', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Taste of Gujarat', max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('cover_image', models.ImageField(blank=True, help_text='Banner for Customer Menu', null=True, upload_to='branding/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('maps_link', models.URLField(blank=True, help_text='Google Maps Location Link', null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Master Switch to Open/Close Restaurant')),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra Service Charge %', max_digits=5)),
                ('packaging_charge', models.IntegerField(default=0, help_text='Fixed charge for Takeaway orders')),
                ('min_order_value', models.IntegerField(default=0, help_text='Minimum bill amount required')),
                ('allow_takeaway', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.TextField(blank=True, help_text='Comma separated permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('is_occupied', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_gst_inclusive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mismatch_reason', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaiterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('salary_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], default='Monthly', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_code', models.CharField(help_text='Login Password', max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='staff_docs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spice', models.CharField(blank=True, max_length=50, null=True)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(default='Pending', max_length=20)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('addons_list', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.table'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('is_veg', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_jain', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_kids_friendly', models.BooleanField(default=True)),
                ('is_chef_special', models.BooleanField(default=False)),
                ('prep_time', models.IntegerField(default=15, help_text='In minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='main.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(default='Cash Drawer', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
