# Generated by Django 4.2.10 on 2026-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
