# Generated by Django 4.2.10 on 2026-03-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderitem_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dependent_inventory_item',
            field=models.ForeignKey(blank=True, help_text='Select the main raw material (e.g., Paneer for Paneer Tikka)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventoryitem'),
        ),
    ]
