# Generated by Django 4.2.10 on 2026-03-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitem_dependent_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_gu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_gu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_gu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
