# Generated by Django 4.2.10 on 2026-03-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_name_gu_category_name_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='dependent_inventory_item',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_gu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_notified',
        ),
    ]
