# Generated by Django 4.2.10 on 2026-03-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_menuitem_dependent_inventory_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dependent_inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventoryitem'),
        ),
    ]
