# Generated by Django 4.2.10 on 2026-03-11 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_remove_category_description_role_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='dependent_inventory_item',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_gu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(default='Cash Drawer', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addons_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overridelog',
            name='authorized_by',
            field=models.CharField(default='Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='overridelog',
            name='reason',
            field=models.TextField(default='General'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridelog',
            name='target',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='allow_takeaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Banner for Customer Menu', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='currency_symbol',
            field=models.CharField(default='Rs', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Master Switch to Open/Close Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Google Maps Location Link', null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='min_order_value',
            field=models.IntegerField(default=0, help_text='Minimum bill amount required'),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='packaging_charge',
            field=models.IntegerField(default=0, help_text='Fixed charge for Takeaway orders'),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra Service Charge %', max_digits=5),
        ),
        migrations.AddField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='staff_docs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='taxsetting',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxsetting',
            name='is_gst_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zreport',
            name='cash_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zreport',
            name='cash_expected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zreport',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zreport',
            name='mismatch_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantsetting',
            name='name',
            field=models.CharField(default='My Restaurant', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantsetting',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g. Taste of Gujarat', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.TextField(blank=True, help_text='Comma separated permissions'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pin_code',
            field=models.CharField(help_text='Login Password', max_length=6),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.table')),
            ],
        ),
    ]
