# Generated by Django 4.2.10 on 2026-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_category_name_gu_remove_category_name_hi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsetting',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
    ]
